### ISSUE TITLE
哔哩哔哩漫画-个人中心页面全白

### ISSUE THREAD

**Issue by siciyuanweilai** [tolking/usercss#12]
希望大佬再优化下这个页面，感谢！！！

**Comment by tolking** [comment]
之前没有注意有这个页面，下周六之前更新版本会加上

**Comment by siciyuanweilai** [comment]
> 之前没有注意有这个页面，下周六之前更新版本会加上

谢谢，辛苦了。。

**Comment by tolking** [comment]
已经处理了，可能会存在部分地方由于我没有数据，会有颜色错误

**Comment by siciyuanweilai** [comment]
> 已经处理了，可能会存在部分地方由于我没有数据，会有颜色错误

目前没发现有什么问题，觉得挺好的。。
