### ISSUE TITLE
README 的 weibo-dark 目录传送门错了

### ISSUE THREAD

**Issue by Geeyun-JY3** [tolking/usercss#37]
指向的是：https://github.com/tolking/usercss/blob/master/weibo-lite/README.md

**Comment by Geeyun-JY3** [comment]
另外，建议分发至 Greasy Fork。Greasy Fork 现已 [支持 UserCSS](https://greasyfork.org/discussions/greasyfork/57226)。

**Comment by tolking** [comment]
看起来 Greasy Fork 是需要 `js` 脚本，这涉及到整个打包流程的变动。我暂时没有时间完成这项工作，欢迎 PR

**Comment by Geeyun-JY3** [comment]
> 需要 `js` 脚本

不需要的吧，现在可以在 Greasy Fork 直接安装 UserCSS，分发会涉及到 `js` 脚本吗？

**Comment by tolking** [comment]
> 不需要的吧，现在可以在 Greasy Fork 直接安装 UserCSS。
抽时间看看
